const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { pool } = require('./db');

const router = express.Router();
const SALT_ROUNDS = 10;

// ── In-memory user cache (token → user payload) ─────────────
// Keyed by userId (UUID). Populated on login/register.
// /me reads from here instead of hitting the DB every request.
const userCache = new Map();

// ── JWT middleware ──────────────────────────────────────────
function authMiddleware(req, res, next) {
  const header = req.headers.authorization;
  if (!header || !header.startsWith('Bearer ')) {
    return res.status(401).json({ success: false, error: 'Token required' });
  }

  const token = header.split(' ')[1];
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.userId           = decoded.userId;
    req.userEmail        = decoded.email;
    req.userFullName     = decoded.fullName;
    req.userRole         = decoded.role || 'user';
    req.userMunicipality = decoded.municipality || null;
    next();
  } catch (err) {
    return res.status(401).json({ success: false, error: 'Invalid or expired token' });
  }
}

// ── Officer-only middleware ──────────────────────────────────
function officerMiddleware(req, res, next) {
  if (req.userRole !== 'municipal_officer') {
    return res.status(403).json({ success: false, error: 'Sadece belediye personeli erişebilir' });
  }
  next();
}

// ── POST /api/auth/register ─────────────────────────────────
router.post('/register', async (req, res) => {
  try {
    const { email, password, fullName, role, municipality } = req.body;

    // Validation
    if (!email || !password || !fullName) {
      return res.status(400).json({
        success: false,
        error: 'Email, password and full name are required'
      });
    }

    if (password.length < 6) {
      return res.status(400).json({
        success: false,
        error: 'Password must be at least 6 characters'
      });
    }

    if (role === 'municipal_officer' && !municipality) {
      return res.status(400).json({
        success: false,
        error: 'Municipality is required for municipal officers'
      });
    }

    // Check if email already exists
    const existing = await pool.query('SELECT id FROM users WHERE email = $1', [email.toLowerCase()]);
    if (existing.rows.length > 0) {
      return res.status(409).json({
        success: false,
        error: 'Email already registered'
      });
    }

    // Hash password and insert — UUID is auto-generated by Postgres
    const passwordHash = await bcrypt.hash(password, SALT_ROUNDS);
    const result = await pool.query(
      'INSERT INTO users (email, password_hash, full_name, role, municipality) VALUES ($1, $2, $3, $4, $5) RETURNING id, email, full_name, role, municipality, created_at',
      [email.toLowerCase(), passwordHash, fullName, role || 'user', role === 'municipal_officer' ? municipality : null]
    );

    const user = result.rows[0];

    // Build user payload and cache it
    const userPayload = {
      id:           user.id,
      email:        user.email,
      fullName:     user.full_name,
      role:         user.role || 'user',
      municipality: user.municipality || null,
      createdAt:    user.created_at
    };
    userCache.set(user.id, userPayload);

    // Embed user info in token so /me never needs the DB
    const token = jwt.sign(
      { userId: user.id, email: user.email, fullName: user.full_name, role: user.role || 'user', municipality: user.municipality || null },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );

    res.status(201).json({ success: true, token, user: userPayload });
  } catch (err) {
    console.error('Register error:', err);
    res.status(500).json({ success: false, error: 'Registration failed' });
  }
});

// ── POST /api/auth/login ────────────────────────────────────
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({
        success: false,
        error: 'Email and password are required'
      });
    }

    // Find user
    const result = await pool.query(
      'SELECT id, email, password_hash, full_name, role, municipality, created_at FROM users WHERE email = $1',
      [email.toLowerCase()]
    );

    if (result.rows.length === 0) {
      return res.status(401).json({
        success: false,
        error: 'Invalid email or password'
      });
    }

    const user = result.rows[0];

    // Compare password
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) {
      return res.status(401).json({
        success: false,
        error: 'Invalid email or password'
      });
    }

    // Cache user info
    const userPayload = {
      id:           user.id,
      email:        user.email,
      fullName:     user.full_name,
      role:         user.role || 'user',
      municipality: user.municipality || null,
      createdAt:    user.created_at
    };
    userCache.set(user.id, userPayload);

    // Embed user info in token so /me never needs the DB
    const token = jwt.sign(
      { userId: user.id, email: user.email, fullName: user.full_name, role: user.role || 'user', municipality: user.municipality || null },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );

    res.json({ success: true, token, user: userPayload });
  } catch (err) {
    console.error('Login error:', err);
    res.status(500).json({ success: false, error: 'Login failed' });
  }
});

// ── GET /api/auth/me ────────────────────────────────────────
// No DB query — user info is read from the JWT payload (set by authMiddleware)
// or from the in-memory cache. Falls back to DB only if both miss (e.g. server restart
// and a very old token that predates the embedded payload fields).
router.get('/me', authMiddleware, async (req, res) => {
  try {
    // 1. Try in-memory cache first
    const cached = userCache.get(req.userId);
    if (cached) {
      return res.json({ success: true, user: cached });
    }

    // 2. Try fields embedded in JWT (no cache, e.g. right after server restart)
    if (req.userEmail && req.userFullName) {
      const userPayload = {
        id:           req.userId,
        email:        req.userEmail,
        fullName:     req.userFullName,
        role:         req.userRole || 'user',
        municipality: req.userMunicipality || null,
        createdAt:    null   // not critical for UI
      };
      userCache.set(req.userId, userPayload);   // warm the cache
      return res.json({ success: true, user: userPayload });
    }

    // 3. Last resort — DB fallback (old tokens without embedded fields)
    const result = await pool.query(
      'SELECT id, email, full_name, role, municipality, created_at FROM users WHERE id = $1',
      [req.userId]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }

    const user = result.rows[0];
    const userPayload = {
      id:           user.id,
      email:        user.email,
      fullName:     user.full_name,
      role:         user.role || 'user',
      municipality: user.municipality || null,
      createdAt:    user.created_at
    };
    userCache.set(user.id, userPayload);   // warm the cache for next time
    res.json({ success: true, user: userPayload });
  } catch (err) {
    console.error('Auth/me error:', err);
    res.status(500).json({ success: false, error: 'Failed to get user info' });
  }
});

module.exports = { router, authMiddleware, officerMiddleware };
